version: '3.9'

services:
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es8
    environment:
      - node.name=es8
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xmx256m -Xms256m # Memory Option
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib8:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kib8
    environment:
      - node.name=kib8
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://es8:9200
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - es8
  
  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.3
    container_name: logstash
    environment:
      - PREVIOUS_MONTH_START=${PREVIOUS_MONTH_START}
      - PREVIOUS_MONTH_END=${PREVIOUS_MONTH_END}
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/logs:/usr/share/logstash/logs
    ports:
      - "9600:9600"
    networks:
      - elastic
    depends_on:
      - es8

volumes:
  esdata:
  kibanadata:
    
networks:
  elastic:
  


